### ISSUE TITLE
Document API predicate reference is not up-to-date with code

### ISSUE THREAD

**Issue by dimas-b** [stargate/docs#136]
https://stargate.io/docs/stargate/1.0/developers-guide/api_ref/openapi_document_ref.html

Some of the features / predicates mentioned in the docs page above are not actually supported as of Stargate v1.0.29.

**Comment by polandll** [comment]
Document v2 API: $eq, $ne, $in, $nin, $gt, $lt, $gte, $lte, $exists. 

Related to https://github.com/stargate/docs/issues/134.
