### ISSUE TITLE
Add environment variable names to starctl options

### ISSUE THREAD

**Issue by ianjevans** [stargate/docs#14]
We currently document the command line options for starctl [1], but need the environment variable equivalents. E.g. `--dc` is `DATACENTER_NAME`.

[1] https://stargate.io/docs/stargate/0.1/developers-guide/starctl.html

**Comment by tlasica** [comment]
I think most value would be for docker compose usage, so possibly close to docker images.
IMO This would be most convenient for the reader.

**Comment by ianjevans** [comment]
Maybe we need a separate topic on using docker compose.
