### ISSUE TITLE
Document `$or` and `$and` operators for the Docs API

### ISSUE THREAD

**Issue by ivansenic** [stargate/docs#145]
In the https://github.com/stargate/stargate/pull/1137, https://github.com/stargate/stargate/pull/1137, https://github.com/stargate/stargate/pull/1080 and https://github.com/stargate/stargate/pull/1061 we added support for the `$or` search in the Docs API. We also added `$and` to be complete here.

Both operators point to the array of the filters. Examples:

* `where={"$or": [{"value": {"$eq": "a"}}, {"value": {"$eq": "b"}}]}`
* `where={"$or": [{"discount": {"$eq": true}}, "$and": [{"price": {"$lt": 200}}, {"discount": {"$eq": false}}]]}`

**Comment by polandll** [comment]
See: https://datastax.jira.com/wiki/spaces/TIB/blog/2022/03/17/3341090889/Complex+WHERE+Clause+with+Stargate+Document+API

**Comment by polandll** [comment]
@ivansenic 

{"$and": [{ "weights.[*].type": { "$eq": "bench press"}}, { "weights.[*].reps": { "$gt": 10}}]}

This where clause fails in swagger ui with the error:
` {
  "description": "Conditions across multiple fields are not yet supported. Found: 3.",
  "code": 400
}`
Why?

**Comment by polandll** [comment]
Thanks @ivansenic. I did try a collection search instead, and I didn't get an error message. However, it just returns the whole document for which the WHERE clause is true. Not useful if you are searching for "in the document" info. I'll keep an eye on the issue you created to extend the capability.

**Comment by polandll** [comment]
https://github.com/stargate/docs/pull/217
