### ISSUE TITLE
Add Document API docs

### ISSUE THREAD

**Issue by ianjevans** [stargate/docs#17]
After Document API Extension is added, add docs for Document API.

Minimum viable product:
- Topic in Developer Guide on enabling Document API.
- Topic in Developer Guide on using Document API.
- Document API reference doc.

We could use OpenAPI/Swagger for the reference since it's REST based. If so, add to `api` dir and possibly rename `oas.yaml` and update `package.json` with new OpenAPI spec file names and build tasks.

**Comment by polandll** [comment]
I'm going to generate Document API docs for namespace/collection, but put in references to REST API for keyspaces/tables. Is that reasonable, @csplinter ?

Also, do I need to edit the oas.yaml file, or is that supplied from somewhere else?

**Comment by polandll** [comment]
Merged the work.
