### ISSUE TITLE
Add a dedicated section in the docs for the auth service - ADD NEW AUTH

### ISSUE THREAD

**Issue by csplinter** [stargate/docs#19]

**Comment by polandll** [comment]
Note to self: Definitely mention the timeout of the auth token.

**Comment by polandll** [comment]
When making new improvements, look at Hasura docs for sample: https://hasura.io/docs/1.0/graphql/core/guides/integrations/auth0-jwt.html

**Comment by polandll** [comment]
PR #53 is preliminary doc.
