### ISSUE TITLE
Fix header links in the docs

### ISSUE THREAD

**Issue by csplinter** [stargate/docs#20]
It seems like using a link such as https://stargate.io/docs/stargate/0.1/developers-guide/cql.html#_using_the_cql_api_using_cqlsh

does not properly snap to the right section

**Comment by polandll** [comment]
I've seen that also, but thought it was only in a local build. Not a problem I've been with antora before, so I'll have to investigate.

**Comment by polandll** [comment]
Need to discuss changes made by Drew in https://github.com/stargate/antora-ui-stargate/blob/master/src/partials/nav-tree.hbs#L4-16.

**Comment by polandll** [comment]
Fixed.
