### ISSUE TITLE
add gRPC quickstart link to left sidebar menu

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/docs#207]
noticed that the gRPC quickstart page is not listed on the left sidebar menu.

![Screen Shot 2022-04-18 at 2 04 28 PM](https://user-images.githubusercontent.com/12115970/163878101-21b8e2b1-2c9a-45a9-9287-3352eac9e0dc.png)

**Comment by polandll** [comment]
grpc quickstart is not real - I shouldn't even have it in the list of pages. Got an update coming soon that should deal with this as well as a slew of other errors.
