### ISSUE TITLE
Invalid comment for params on Composability: StargateSwap.sol page

### ISSUE THREAD

**Issue by behnammohammadkhani** [stargate/docs#212]
https://stargateprotocol.gitbook.io/stargate/composability-stargateswap.sol
On top of swap method we have some description about params. please change "Dealine" comment because it is invalid.

**Comment by tatu-at-datastax** [comment]
@behnammohammadkhani I think this is filed in the wrong place; you may be looking for this thing:

https://consensys.net/blog/cryptoeconomic-research/stargate-a-fully-composable-cross-chain-bridge/

or something else (page you linked to points to https://stargate.finance/ ). But as far as I can see, this is not related to Stargate API gateway that this repo is about.
I don't know where the issue tracker you want is, but this is not it I think.
