### ISSUE TITLE
Update Stargate docs to reflect deprecation of Cassandra 3.11 support

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/docs#235]
Based on discussion https://github.com/stargate/stargate/discussions/2242, document the Cassandra 3.11 persistence module as being deprecated and scheduled for removal in Stargate v3.

**Comment by jeffreyscarpenter** [comment]
Should include at minimum 
- https://stargate.io/docs/latest/concepts/concepts.html
- https://stargate.io/docs/latest/install/install_cass_3x.html

**Comment by polandll** [comment]
This issue was closed with a PR #241.
