### ISSUE TITLE
Separate swagger URLs for docs API vs REST API in Stargate v2

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/docs#244]
On the page https://stargate.io/docs/latest/develop/tooling.html#swagger-resources, there are two issues in the section shown below:
 
![Screenshot 2022-12-21 at 2 24 33 PM](https://user-images.githubusercontent.com/12115970/209006716-182fe3fb-c2cf-4135-816a-7f97791b5d15.png)

1. The URL is missing `//` - it should be `http://localhost:8180/swagger-ui/` 
2. For Stargate v2, the Docs API Swagger is at a different port: `http://localhost:8180/swagger-ui/`

**Comment by polandll** [comment]
Completed.
