### ISSUE TITLE
Add documentation for metrics

### ISSUE THREAD

**Issue by csplinter** [stargate/docs#28]
@olim7t added metrics in https://github.com/stargate/stargate/pull/39 and we should have a section in documentation that provides instructions for sending these metrics to Prometheus and reporting with Grafana.

**Comment by polandll** [comment]
cql_org_apache_cassandra_metrics_* and persistence_cassandra_311_org_apache_cassandra_metrics_*, I presume, are the Apache C* metrics. 
graphql_io_stargate_GraphQLSchema_* and graphql_io_stargate_GraphQL_* are Stargate GraphQL API
restapi_io_stargate_web_docsapi_* are Stargate Documents API
restapi_io_stargate_web_resource_* and restapi_io_stargate_web_v2_* are Stargate REST API

**Comment by polandll** [comment]
Also submitted PR to stargate/docker-images: https://github.com/stargate/docker-images/pull/22
