### ISSUE TITLE
Quickstart links not working

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/docs#31]
REST QuickStart at https://stargate.io/docs/stargate/0.1/developers-guide/rest.html not working
GraphQL QuickStart at https://stargate.io/docs/stargate/0.1/developers-guide/graphql.html not working

When clicking either QuickStart link the URL changes to an anchor but the page doesn't go anywhere.

**Comment by polandll** [comment]
https://github.com/stargate/docs/pull/33 waiting for review

**Comment by polandll** [comment]
fixed.
