### ISSUE TITLE
Use environment variables instead of args in "Installing Stargate with an existing Cassandra cluster"

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/docs#32]
For this https://stargate.io/docs/stargate/0.1/developers-guide/existing_cstar.html we should be using environment variables instead of args so that the start script uses the IP of the docker container.

```sh
docker run --name stargate \
  -d stargateio/stargate-3_11:v0.0.6 \
  -e CLUSTER_NAME=stargate \
  -e SEED=127.0.0.1 \
  -e CLUSTER_VERSION=3.11 \
  -e SIMPLE_SNITCH=true \
  -e ENABLE_AUTH=true
```

**Comment by polandll** [comment]
I need to check with Jeremy to understand the final resolution of what to document.

**Comment by dougwettlaufer** [comment]
He was able to get it working building from source but still had trouble with the docker image. Granted it might have been EC2 related but we'll have to see.

**Comment by polandll** [comment]
@dougwettlaufer Is a `LISTEN_ADDRESS` needed? Seems like it would be.

**Comment by polandll** [comment]
Also, @dougwettlaufer  what about the ports? Do they need to be mapped?

**Comment by dougwettlaufer** [comment]
`LISTEN_ADDRESS` is not needed in docker because the script determines it and sets if not provided https://github.com/stargate/stargate/blob/master/starctl#L87-L92

If you're using nonstandard ports then, yes, they can be set but if not provided we'll use the standard 7000 for gossip and 9042 for cql.
