### ISSUE TITLE
Adjust Document: GraphQL Adding Rows

### ISSUE THREAD

**Issue by ds-steven-matison** [stargate/docs#36]
Not really an issue, but after figuring it out the hardway I think the first code snippet should not reference the values' data object as "data:" but should use "value:" as provided in the second code snippet.

  https://docs.astra.datastax.com/docs/adding-rows-in-your-table-using-graphql

**Comment by polandll** [comment]
This repo is not the source that you cite. I'll let the Astra docs writer know.

**Comment by polandll** [comment]
Closing issue, and let the Astra docs writer know.
