### ISSUE TITLE
doc link broken

### ISSUE THREAD

**Issue by mthahir** [stargate/docs#47]
The links to Quickstart in the following URL, all of them, are broken:
https://github.com/stargate/docs/blob/master/modules/quickstart/nav.adoc

**Comment by polandll** [comment]
Those are nav files used to create the docs with antora publishing. That page as rendered is not expected to point to "valid" URLs. If you go to: https://stargate.io/docs/stargate/0.1/quickstart/quickstart.html, you'll see the rendered pages.
