### ISSUE TITLE
Broken Links on API Ref page

### ISSUE THREAD

**Issue by denisekgosnell** [stargate/docs#51]
The links on this page:
https://stargate.io/docs/stargate/0.1/developers-guide/api_ref/apiref.html#openapi_document_ref.adoc

To the following pageS:
REST API 
DOCUMENT API

Do not redirect to another page. 

Please send them to:

REST API --> https://stargate.io/docs/stargate/0.1/developers-guide/api_ref/openapi_rest_ref.html
DOCUMENT API --> https://stargate.io/docs/stargate/0.1/developers-guide/api_ref/openapi_document_ref.html

Thank you!

**Comment by polandll** [comment]
Fixed with a direct commit and republish.
