### ISSUE TITLE
Add additional examples to Document API for json-path

### ISSUE THREAD

**Issue by polandll** [stargate/docs#62]
Similar to the additions to GraphQL.

**Comment by dougwettlaufer** [comment]
Probably on your radar but just checking. Will an expanded explanation of JSON path be added as part of this update? In the API spec we mention `document-path = a JSON path` but we never really expand on it.

@EricBorczuk would linking to something like https://github.com/jsurfer/JsonSurfer or https://goessner.net/articles/JsonPath/ be appropriate?

**Comment by 012345** [comment]
Example for folks while docs update is pending 

/collections/hello_docs/062d804f-7294-45c9-87c8-087c6938e942?where={"employees.*.name":{"$eq":"john"}}'&fields=["name","salary","active"] 

would return 

{
    "documentId": "062d804f-7294-45c9-87c8-087c6938e942",
    "data": [
        {
            "employees": {
                "[1]": {
                    "active": true,
                    "name": "john",
                    "salary": 56000
                }
            }
        }
    ]

**Comment by EricBorczuk** [comment]
I think that https://goessner.net/articles/JsonPath/ is pretty much the same as the Json paths we support, so that could be an appropriate link to include.

There is one notable difference between JsonPath described in that link and the one docs API uses, which is when dealing with array indexes, JsonPath is something like `x.store.book[0].title`, but our API is like `x.store.book.[0].title`

**Comment by polandll** [comment]
Changing the title of this issue, because it was not really accurate.

**Comment by polandll** [comment]
wildcard (*) and x.store.book.[0].title are the only supported options. 

These work due to the document shredding done to store docs in C*.

**Comment by polandll** [comment]
Still need x.store.book.[0].title type example. Put in a wildcard.

**Comment by polandll** [comment]
Two items: 
1. change "json-path" to "document-path" in the docs.
2. Add an example with an array to add an array-indexed example. Do it with the weights (sets of reps), but use this example as a guide:
{
  "data": {
    "Joey": {
      "firstname": "Joey",
      "lastname": "Doe",
      "friends": [
        {"firstname": "Mary", "lastname": "Smith"},
        {"firstname": "James", "lastname": "Doe"}
      ]
    },
    "Martha": {
      "firstname": "Martha",
      "lastname": "Smith",
      "friends": [
        {"firstname": "Mary", "lastname": "Smith"},
        {"firstname": "Joey", "lastname": "Doe"}
      ]
    }
  }
}


well for the above, both documents would match {"friends.[0].firstname": { "$eq": "Mary"}}

**Comment by polandll** [comment]
DataStax Stargate Document API
The query string is pretty similar in spirit to what you'd find with Mongo.
Here are some sample where clauses to give an idea:
{"name": {"$eq": "Eric"}} - simple enough, matches documents that have a field name with value Eric
{"a.age": {"$gt": 0}} - You can also reference nested fields in a document
{"friends.[0].name": {"$in": ["Cassandra"]}} - Array elements are referenced using [], this would match if the document's first friend is named Cassandra.
{"friends..age": {"$gte": 24}} - Wildcard can be used to match any element in an array, or any field at a particular level of nesting. This matches any friend whose age is >= 24.
Show less

**Comment by polandll** [comment]
https://github.com/stargate/docs/pull/217
