### ISSUE TITLE
Please add GraphQL API details to API Reference page

### ISSUE THREAD

**Issue by denisekgosnell** [stargate/docs#83]
Hello!  I was digging through the different APIs on the [API Reference page](https://stargate.io/docs/stargate/1.0/developers-guide/api_ref/apiref.html). I wanted to better understand the different routes to set up in my app based on access pattern.

Can we please add URL level reference to the different GraphQL APIs?

I believe the root URLs are:

- /graphql-schema 
- /graphql/library

Clarity and examples of how to use the API outside of the playground would be very helpful. Thank you!

**Comment by polandll** [comment]
Yep, many, many updates coming for all the APIs, including GraphQL. And the roots URLs are mentioned in the docs already, they are:
/graphql-schema
/graphql/<namespace>

**Comment by denisekgosnell** [comment]
@polandll Thank you! I missed them in the docs at first. I am excited for the upcoming changes. (with patience!)  :)
