### ISSUE TITLE
Add token TTL information to the authentication section in the quick start guides

### ISSUE THREAD

**Issue by mpenick** [stargate/docs#91]
We should mention that tokens expire with sliding window of 1800 seconds (30 minutes) by default and  can be changed using the `"stargate.auth_tokenttl"` property.

**Comment by polandll** [comment]
And can you give me an example of using that property, please, @mpenick ?

**Comment by dougwettlaufer** [comment]
@polandll that will be a startup `-D` parameter to increase or decrease the TTL for the token. So if you want the token to have a shorter TTL you would start up stargate like 

```
JAVA_OPTS='-Dstargate.auth_tokenttl=100' ./starctl \
--developer-mode --cluster-name test --cluster-version 3.11 --enable-auth
```

**Comment by polandll** [comment]
Thanks @dougwettlaufer. Are they any other JAVA_OPTS that get commonly used that I should add to the starctl page at the same time?

**Comment by dougwettlaufer** [comment]
Other than heap settings, which will be deploy environment specific, not really.
